name: Deploy CI Report to GitHub Pages

on:
  workflow_run:
    workflows: ["ProjectPilotAI Artifact Workflow"]
    types:
      - completed

jobs:
  deploy-report:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download report from artifacts
        uses: actions/download-artifact@v4
        with:
          name: projectpilotai-report
          path: ./public

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit to gh-pages
        run: |
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages
          rm -rf *
          mv public/projectpilotai_ci_report.html index.html
          git add .
          git commit -m "🧾 Update CI report [skip ci]" || echo "No changes to commit"
          git push origin gh-pages
